instagram/config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  devise_for :users
  resources :locations
  get 'home/index'
  get 'locations/index'
  get 'main/index'


  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

instagram/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

instagram/app/models/home.rb
class Home < ApplicationRecord
end

instagram/app/models/location.rb
class Location < ApplicationRecord
	geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

instagram/app/models/photo.rb
class Photo < ApplicationRecord
	validates :thumbnail_url, :owner, :link, :presence => true

  def get_recent_media
    recent_media = Instagram.tag_recent_media('fashion')

    recent_media.each do |media|
      Photo.create(
        link: media.link,
        owner: media.caption.from.username,
        thumbnail_url: media.images.thumbnail.url
      )
    end
  end
end

instagram/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

instagram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!, only: :show

  private
  def authenticate_user
    redirect_to new_user_registration_url unless user_signed_in?
  end
end

instagram/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
@user=Instagram.user_follows
	@media_arr = Array.new
for user in @user
	@instagram = Instagram.user_recent_media(user.id)
	@media_arr.push(@instagram)
end
end
end

instagram/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all.page(params[:page]).per(4)
    p @locations
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @latln = Location.find(params[:id])
    @check_in=Instagram.location_search(@latln.latitude, @latln.longitude, @latln.distance)
    @hash = Gmaps4rails.build_markers(@check_in) do |check_in, marker|
    marker.lat check_in.latitude
    marker.lng check_in.longitude
end

  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude, :distance)
    end
end

instagram/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

instagram/app/helpers/application_helper.rb
module ApplicationHelper
end

instagram/app/helpers/home_helper.rb
module HomeHelper
end

instagram/app/helpers/location_recent_media_helper.rb
module LocationRecentMediaHelper
end

instagram/app/helpers/locations_helper.rb
module LocationsHelper
end

instagram/app/helpers/main_helper.rb
module MainHelper
end

instagram/app/views/home/index.html.erb
  <div class="row">
  <h1>Instagram Lookup</h1>
    <% for i in 0..@media_arr.count-1 %>
      <div class="flexslider">
        <ul class="slides">
          <% @media_arr[i].each do |instagram| %>

          <li>
              <%= image_tag instagram.images.standard_resolution.url%>
              <p class="flex-caption"><strong>User: </strong><%= instagram.user.username %></p>
              <% if instagram.caption %>
              <p class="flex-caption"><strong>Caption: </strong><%= instagram.caption.text %></p>
              <% end %>
          </li>
          <% end %>

        </ul>
      </div>
    <% end %>
  </div>

<div class="back">
<%=link_to root_path do %><i class="fa fa-hand-o-left " aria-hidden="true"></i><% end %>
</div>

instagram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyCWKtxSQTUUraysWlHfzv0cUZ3TR3LQK4o"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>

  <body>



<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Social Networking Connections</h3>
              <nav>
                <ul class="nav masthead-nav">
                 <li class="active"><%= link_to root_path do %><i class="fa fa-home fa-fw" aria-hidden="true"></i> Home <% end %></li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" >Manage <span class="fa fa-list-ul" title="Toggle dropdown menu"></span></a>
          <ul class="dropdown-menu ">
            <li><%= link_to 'Posts', home_index_path%></li>
            <li><%= link_to 'Location',locations_url %></li>
          </ul>
      </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" >
          <i class="fa fa-user fa-fw"></i>
          <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <% unless user_signed_in? %>
            <li><%= link_to new_user_registration_path do %><i class="fa fa-user-plus" aria-hidden="true"></i> Sign up <% end %></li>
            <li><%= link_to new_user_session_path do %><i class="fa fa-sign-in" aria-hidden="true"></i> Log In <% end %></li>
          <% end %>
            <li><%= link_to destroy_user_session_path , method: :delete do %><i class="fa fa-sign-out" aria-hidden="true"> Log Out <% end %></i></li>
        </ul>
      </li>


                </ul>
              </nav>
            </div>
          </div>



          <% if params[:controller] == 'main' %>
          <div class="inner cover">
            <h1 class="cover-heading">Wonolo Coding Challenge.</h1>
            <p class="lead">Create a Rails 4 website that allows the users to search for instagram posts in location specified by the user.</p>
            <p class="lead">
            <%= link_to 'Read more', locations_url, class:'btn btn-lg btn-default'%>
            </p>
          </div>
          <% end %>

          <div class="inner cover">
            <%= yield %>
          </div>


        </div><!--/.nav-collapse -->
    </div>
</div>

    <footer>

    <div class="container">
    <div class="icon">
    <ul class="social-icons icon-circle icon-rotate list-unstyled list-inline"> 
    <a  href="https://www.facebook.com" target="_blank"><i class="fa fa-facebook-square fa-3x pull-left" aria-hidden="true" ></i></a>
    <a  href="https://www.youtube.com" target="_blank"><i class="fa fa-youtube-square fa-3x pull-left" aria-hidden="true"></i></a>
    <a  href="https://www.github.com" target="_blank"><i class="fa fa-github-square fa-3x pull-left" aria-hidden="true"></i></a>
    <a  href="https://www.twitter.com" target="_blank"><i class="fa fa-twitter-square fa-3x pull-left" aria-hidden="true"></i></a>
    <a href="https://plus.google.com" target="_blank"><i class="fa fa-google fa-3x pull-left" aria-hidden="true"></i></a>
    </ul>
      <p>Copyright &copy; 2017, All Rights Resrved </p>
       <div class="col-sm-6">
      <ul class="menu">
            <li><%= link_to 'About' %> | </li>
            <li><%= link_to 'Term of Service' %> | </li>
            <li><%= link_to 'Privacy Policy' %> | </li>
            <li><a href="/en/sponsors">Sponsors</a></li>
          </ul>
          </div>
    </div>
    </div>

  </footer>
  </body>
</html>

instagram/app/views/locations/_form.html.erb
<%= simple_form_for @location do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :address %><br />
    <%= form.text_field :address, id: :location_address %><br />
  </div>

  <div class="form-group">
    <%= form.label :latitude %><br />
    <%= form.text_field :latitude, id: :location_latitude %><br />
  </div>

  <div class="form-group">
    <%= form.label :longitude %><br />
    <%= form.text_field :longitude, id: :location_longitude %><br />
  </div>

 <div class="form-group">
    <%= form.label :radius %><br />
    <%= form.text_field :distance, id: :location_distance %><br />
</div>

  <div class="actions">
    <%= form.submit 'Submit',:class => 'btn btn-lg btn-default' %>
  </div>
<% end %>

instagram/app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location,class:'btn btn-lg btn-info' %>
<%= link_to 'Back', locations_url,class:'btn btn-lg btn-primary' %>

instagram/app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>
<br>



<table class="display table" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Radius</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= location.distance %></td>
    <td><%= link_to 'Show', location,class:'btn btn-lg btn-info' %>  <%= link_to 'Edit', edit_location_path(location),class:'btn btn-lg btn-warning'  %>  <%= link_to 'Delete', location,class:'btn btn-lg btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div> <%= paginate @locations, theme: 'twitter-bootstrap-3' %></div>
<div> <%= link_to 'New Location', new_location_path,class:'btn btn-lg btn-default' %></div>

instagram/app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

instagram/app/views/locations/show.html.erb
<div id="map" ></div>


<script>

var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'map'}}, function(){
 markers = handler.addMarkers(<%=raw @hash.to_json %>); 
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});


</script>

<div class="back">
<%=link_to locations_url do %><i class="fa fa-hand-o-left " aria-hidden="true"></i><% end %>
</div>